LucidtechAI/las-sdk-js

- Makefile
- packages/las-sdk-browser/package.json
- packages/las-sdk-core/package.json
- packages/las-sdk-core/src/client.spec.ts
- packages/las-sdk-core/src/client.ts
- packages/las-sdk-node/package.json
Fixes #56, fixes #57, fixes #58
> add GET /transitions/:Id, GET /workflows/:Id and DELETE /transitions/:Id

- packages/las-sdk-browser/package-lock.json
- packages/las-sdk-browser/package.json
- packages/las-sdk-core/package.json
- packages/las-sdk-core/src/client.spec.ts
- packages/las-sdk-core/src/client.ts
- packages/las-sdk-core/src/types.ts
- packages/las-sdk-node/package-lock.json
- packages/las-sdk-node/package.json
Plus some formatting... 🤓
Fixes #60, fixes #61, fixes #62
> add sendHeartbeat, startTime and imageQuality fields

- packages/las-sdk-core/src/types.ts
> Added proprocessConfig and fieldConfig to Model

- packages/las-sdk-core/src/client.spec.ts
- packages/las-sdk-core/src/client.ts
- packages/las-sdk-core/src/types.ts
> Added createAppClient, listAppClients, deleteAppClient

- packages/las-sdk-core/src/client.spec.ts
- packages/las-sdk-core/src/types.ts
> Added numDocuments to Batch

- packages/las-sdk-browser/package.json
- packages/las-sdk-core/package.json
- packages/las-sdk-node/package.json
- @lucidtech/las-sdk-browser@3.7.0
- @lucidtech/las-sdk-core@3.7.0
- @lucidtech/las-sdk-node@3.7.0
> Publish 3.7.0

- packages/las-sdk-browser/package.json
- packages/las-sdk-core/package.json
- packages/las-sdk-node/package.json
- @lucidtech/las-sdk-browser@3.7.1
- @lucidtech/las-sdk-core@3.7.1
- @lucidtech/las-sdk-node@3.7.1
> Release 3.7.1

- packages/las-sdk-core/src/client.spec.ts
- packages/las-sdk-core/src/types.ts
> Added batchId to deleteDocuments query

- packages/las-sdk-core/src/client.spec.ts
- packages/las-sdk-core/src/types.ts
> Added retentionInDays, storageLocation, containsPersonallyIdentifiableInformation to Batch

- packages/las-sdk-browser/package.json
- packages/las-sdk-core/package.json
- packages/las-sdk-node/package.json
- @lucidtech/las-sdk-browser@3.8.0
- @lucidtech/las-sdk-core@3.8.0
- @lucidtech/las-sdk-node@3.8.0
> Publish 3.8.0

- packages/las-sdk-core/src/client.spec.ts
- packages/las-sdk-core/src/client.ts
- packages/las-sdk-core/src/types.ts
Fixes #91, fixes #92, fixes #75
> add getWorkflowExecution, updateWorkflowExecution, getTransitionExecution

- packages/las-sdk-browser/package.json
- packages/las-sdk-core/package.json
- packages/las-sdk-node/package.json
- @lucidtech/las-sdk-browser@3.9.0
- @lucidtech/las-sdk-core@3.9.0
- @lucidtech/las-sdk-node@3.9.0
> Update version to 3.9.0

- CHANGELOG.md
- packages/las-sdk-browser/package.json
- packages/las-sdk-core/package.json
- packages/las-sdk-node/package.json
- @lucidtech/las-sdk-browser@4.0.0
- @lucidtech/las-sdk-core@4.0.0
- @lucidtech/las-sdk-node@4.0.0
> Update version to 4.0.0

- packages/las-sdk-browser/package.json
- packages/las-sdk-core/package.json
- packages/las-sdk-node/package.json
- @lucidtech/las-sdk-browser@4.1.0
- @lucidtech/las-sdk-core@4.1.0
- @lucidtech/las-sdk-node@4.1.0
> Update version to 4.1.0

- packages/las-sdk-browser/package.json
- packages/las-sdk-core/package.json
- packages/las-sdk-node/package.json
- @lucidtech/las-sdk-browser@4.2.0
- @lucidtech/las-sdk-core@4.2.0
- @lucidtech/las-sdk-node@4.2.0
> Update version to 4.2.0

- CHANGELOG.md
- packages/las-sdk-core/src/client.spec.ts
- packages/las-sdk-core/src/client.ts
- packages/las-sdk-core/src/types.ts
> Added getOrganization, updateOrganization

- packages/las-sdk-browser/package.json
- packages/las-sdk-core/package.json
- packages/las-sdk-node/package.json
- @lucidtech/las-sdk-browser@4.3.0
- @lucidtech/las-sdk-core@4.3.0
- @lucidtech/las-sdk-node@4.3.0
> Update version to 4.3.0

- packages/las-sdk-browser/package.json
- packages/las-sdk-core/package.json
- packages/las-sdk-node/package.json
- @lucidtech/las-sdk-browser@4.3.1
- @lucidtech/las-sdk-core@4.3.1
- @lucidtech/las-sdk-node@4.3.1
> Update version to 4.3.1

- packages/las-sdk-browser/package-lock.json
- packages/las-sdk-browser/package.json
- packages/las-sdk-core/package.json
- packages/las-sdk-node/package-lock.json
- packages/las-sdk-node/package.json
- @lucidtech/las-sdk-browser@4.4.0
- @lucidtech/las-sdk-core@4.4.0
- @lucidtech/las-sdk-node@4.4.0
> Update version to 4.4.0

- CHANGELOG.md
- packages/las-sdk-core/src/client.spec.ts
- packages/las-sdk-core/src/types.ts
`numDocuments` -> `numberOfDocuments`
> fix: Dataset properties

- packages/las-sdk-browser/package-lock.json
- packages/las-sdk-browser/package.json
- packages/las-sdk-core/package.json
- packages/las-sdk-node/package-lock.json
- packages/las-sdk-node/package.json
- @lucidtech/las-sdk-browser@4.4.1
- @lucidtech/las-sdk-core@4.4.1
- @lucidtech/las-sdk-node@4.4.1
> Update version to 4.4.1

- packages/las-sdk-browser/package-lock.json
- packages/las-sdk-browser/package.json
- packages/las-sdk-core/package.json
- packages/las-sdk-node/package-lock.json
- packages/las-sdk-node/package.json
- @lucidtech/las-sdk-browser@4.5.0
- @lucidtech/las-sdk-core@4.5.0
- @lucidtech/las-sdk-node@4.5.0
> Update version to 4.5.0

- packages/las-sdk-core/src/types.ts
> fix: accept array of transitionExecution status

- README.md
- examples/web/src/index.js
- packages/las-sdk-browser/src/credentials.spec.ts
- packages/las-sdk-browser/src/credentials.ts
- packages/las-sdk-core/src/client.spec.ts
- packages/las-sdk-core/src/client.ts
- packages/las-sdk-core/src/credentials.spec.ts
- packages/las-sdk-core/src/credentials.ts
- packages/las-sdk-core/src/helpers.ts
- packages/las-sdk-core/src/types.ts
- packages/las-sdk-node/src/credentials.ts
Breaking change :warning: 
Fix #130
> remove all use of apikey

- packages/las-sdk-browser/package-lock.json
- packages/las-sdk-browser/package.json
- packages/las-sdk-core/package.json
- packages/las-sdk-node/package-lock.json
- packages/las-sdk-node/package.json
- @lucidtech/las-sdk-browser@5.0.2
- @lucidtech/las-sdk-core@5.0.2
- @lucidtech/las-sdk-node@5.0.2
> Update version to 5.0.2

- CHANGELOG.md
- packages/las-sdk-browser/package.json
- packages/las-sdk-core/package.json
- packages/las-sdk-core/src/client.spec.ts
- packages/las-sdk-core/src/client.ts
- packages/las-sdk-core/src/types.ts
- packages/las-sdk-node/package.json
Fix #178, fix #177, fix #176, fix #175
> API changes

- CHANGELOG.md
- packages/las-sdk-browser/package.json
- packages/las-sdk-core/package.json
- packages/las-sdk-core/src/types.ts
- packages/las-sdk-node/package.json
> Add metadata to User, trainingId to PredictionResponse

- CHANGELOG.md
- packages/las-sdk-browser/package.json
- packages/las-sdk-core/package.json
- packages/las-sdk-core/src/client.plans.spec.ts
- packages/las-sdk-core/src/client.spec.ts
- packages/las-sdk-core/src/client.trainings.spec.ts
- packages/las-sdk-core/src/client.ts
- packages/las-sdk-core/src/types/appClient.ts
- packages/las-sdk-core/src/types/role.ts
- packages/las-sdk-core/src/types/user.ts
- packages/las-sdk-node/package.json
- Add `listRoles` and `getRole` methods
- Update all user and app-client types to have roleIds property
- Fix broken tests
> feat: add role methods
